### ISSUE TITLE
Limitsearch: image not found (even so it is there)

### ISSUE THREAD

**Issue by teamdocs** [teamdocs/kantu2018#27]
Please see the attached test macro. The first Limit test with the "to" image works fine.

But the second test with "Copyfish" image not: After limiting the area I expect it finds the first occurence, but it does not find anything -why is this? _(Idea: could it be the scroll?)_

[001testarea - copyfish.zip](https://github.com/teamdocs/kantu2018/files/1650250/001testarea.-.copyfish.zip)

![copyfish search1](https://user-images.githubusercontent.com/20772857/35199264-254f05f6-fefc-11e7-81cc-82e240e251b1.jpg)

**Comment by kuznetsoffandrey** [comment]
Fixed

**Comment by teamdocs** [comment]
Hmm... the above test macro still fails with "image not found", does it work for you?

**Comment by kuznetsoffandrey** [comment]
In the script Command 11 has Type pinkframe but red cross as an image. It is not found obviously. Maybe there should be another scenario for the editor.

**Comment by teamdocs** [comment]
Question: How does LimitSearchArea work now? You search the whole screenshot and throw away results that do not match, or you just search the new small area?

Another question: Can we mark the limited search area visually? So users sees what part is searched? (not  part of the specs, but nice to have). I could be like make everything grey except the new search area.

**Comment by teamdocs** [comment]
>pinkframe but red cross as an image

not in my case. But the searched image was **partly** outside the search area, that is why it was not found  => so the ticket itself can be closed. I leave it only open for the questions above.

**Comment by kuznetsoffandrey** [comment]
Now I just search the specific area.

Yes, we can add this GUI functionality for the command. We can try several cases to see which one is more suitable for the user

**Comment by teamdocs** [comment]
Ok,  I will close this ticket for now and add the UI change to the backlog.
